inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Bundler/OrderedGems:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false
