// Typelizer digest 6d052300cd33f1c1847d5e5bcfa1a70f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Account = {
  id: number;
  email: string;
  status: "unverified" | "verified" | "closed";
}

export default Account;
