// Typelizer digest 9c0aa753aadec61597aae532118e4d4d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Profile} from '@/types'

type Auth = {
  profile: Profile;
}

export default Auth;
