// Typelizer digest cad00c91ce4e91206f754de6373fad5c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Profile} from '@/types'

type GarageListItem = {
  id: number;
  title: string | null;
  description: string | null;
  description_plain: string | null;
  state: string | null;
  created_at: string;
  creator: Profile;
}

export default GarageListItem;
