// Typelizer digest f176ec62d1b603c7414c8d96766b8057
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Profile} from '@/types'

type GarageListItem = {
  id: number;
  title: string | null;
  description: string | null;
  state: string | null;
  created_at: string;
  creator: Profile;
}

export default GarageListItem;
