// Typelizer digest 4a5fbfb76668edc0ec1740ed2cbb8918
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Profile} from '@/types'

type GarageList = {
  id: number;
  name: string;
  description: string | null;
  created_at: string;
  owner: Profile;
  members_count: number;
}

export default GarageList;
