// Typelizer digest 69f27b32276af67813a047ed601db5e0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Account} from '@/types'

type Profile = {
  id: number;
  first_name: string | null;
  last_name: string | null;
  handle: string | null;
  account: Account;
}

export default Profile;
