// Typelizer digest eab446289062e8a43bfb41a4b3831419
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Flash, Auth} from '@/types'

type SharedProps = {
  flash: Flash;
  auth: Auth;
}

export default SharedProps;
